## Analyse process files nodes and edges

In [1]:
import sys
import pandas as pd
sys.path.append("../scripts")
from graph_analysis import load_active_databases, analyze_processed_databases

## Analyse nodes categories

In [2]:
# Dynamically analyze active databases from databases_config.yaml
results = analyze_processed_databases(config_path="../../config/databases_config.yaml", base_dir="../../data/processed/finals")

print("Nodes by Category:")
display(results["categories"])

print()
print("Nodes by Prefix:")
display(results["prefixes"])

print()
print("Unique nodes across databases:")
display(results["unique_nodes"])

Nodes by Category:

,GO,HP,MONDO,ENSEMBL,GOA,HPOA,Disgenet,Uberon,CL,Bgee,RNACentral,DIANA-TarBase,NPInter,STRING
biolink:BiologicalProcess,30723,0,0,0,30723,0,0,0,7023,0,0,0,0,0
biolink:MolecularActivity,12614,0,0,0,12614,0,0,0,376,0,0,0,0,0
biolink:CellularComponent,4519,0,0,0,4519,0,0,0,294,0,0,0,0,0
biolink:OntologyClass,3756,52,10756,0,3756,0,0,352,570,0,0,0,0,0
biolink:PhenotypicFeature,0,19162,4807,0,0,19162,8550,0,0,0,0,0,0,0
biolink:Disease,0,0,28746,0,0,8399,11237,0,0,0,0,0,0,0
biolink:AnatomicalEntity,0,0,5348,0,0,0,0,15725,4624,313,0,0,0,0
biolink:OrganismTaxon,0,0,1832,0,0,0,0,0,135,0,0,0,0,0
biolink:ChemicalSubstance,0,0,1214,0,0,0,0,0,651,0,0,0,0,0
biolink:Cell,0,0,1196,0,0,0,0,271,2909,16,0,0,0,0
biolink:SequenceFeature,0,0,85,0,0,0,0,0,0,0,0,0,0,0
biolink:Protein,0,0,0,141653,60435,0,0,0,709,0,0,0,845,19114
biolink:Gene,0,0,0,23675,0,0,18361,0,0,59509,24490,19561,2181,0
biolink:RNAProduct,0,0,0,0,22776,0,0,0,0,0,62925,901,46426,0
biolink:MacromolecularComplexMixin,0,0,0,0,1912,0,0,0,0,0,0,0,0,0
biolink:NamedThing,0,0,0,0,0,0,0,0,43,0,0,0,0,0

Nodes by Prefix:

,GO,HP,MONDO,ENSEMBL,GOA,HPOA,Disgenet,Uberon,CL,Bgee,RNACentral,DIANA-TarBase,NPInter,STRING
GO,51502,0,4041,0,51502,0,0,0,7694,0,0,0,0,0
RO,79,5,225,0,79,0,0,86,247,0,0,0,0,0
OIO,15,18,24,0,15,0,0,82,13,0,0,0,0,0
OBO,7,8,720,0,7,0,0,114,42,0,0,0,0,0
BFO,5,3,31,0,5,0,0,5,21,0,0,0,0,0
IAO,4,4,78,0,4,0,0,10,5,0,0,0,0,0
HP,0,19162,4807,0,0,19162,8550,0,0,0,0,0,0,0
dc,0,7,15,0,0,0,0,6,3,0,0,0,0,0
dcterms,0,4,6,0,0,0,0,4,3,0,0,0,0,0
rdfs,0,2,3,0,0,0,0,3,1,0,0,0,0,0
owl,0,1,1,0,0,0,0,1,0,0,0,0,0,0
MONDO,0,0,28746,0,0,8399,11237,0,0,0,0,0,0,0
UBERON,0,0,5348,0,0,0,0,15725,4624,313,0,0,0,0
http,0,0,3972,0,0,0,0,5,0,0,0,0,0,0
NCBITaxon,0,0,1832,0,0,0,0,0,137,0,0,0,0,0
CHEBI,0,0,1214,0,0,0,0,0,651,0,0,0,0,0
CL,0,0,1196,0,0,0,0,271,2909,16,0,0,0,0
ENVO,0,0,463,0,0,0,0,0,0,0,0,0,0,0
PATO,0,0,397,0,0,0,0,0,189,0,0,0,0,0
CHR,0,0,310,0,0,0,0,0,0,0,0,0,0,0
FOODON,0,0,203,0,0,0,0,0,0,0,0,0,0,0
NBO,0,0,116,0,0,0,0,0,2,0,0,0,0,0
NCIT,0,0,87,0,0,0,0,0,0,0,0,0,0,0
SO,0,0,85,0,0,0,0,0,2,0,0,0,0,0
BSPO,0,0,25,0,0,0,0,30,24,0,0,0,0,0
MF,0,0,14,0,0,0,0,0,0,0,0,0,0,0
MFOMD,0,0,12,0,0,0,0,0,0,0,0,0,0,0
OGMS,0,0,5,0,0,0,0,0,0,0,0,0,0,0
skos,0,0,5,0,0,0,0,0,0,0,0,0,0,0
https,0,0,2,0,0,0,0,3,0,0,0,0,0,0
foaf,0,0,1,0,0,0,0,3,1,0,0,0,0,0
UNIPROTKB,0,0,0,141653,60435,0,0,0,709,0,0,0,845,19114
ENSEMBL,0,0,0,23675,0,0,18361,0,0,59509,24490,19561,2181,0
RNACENTRAL,0,0,0,0,22776,0,0,0,0,0,62925,901,46426,0
COMPLEXPORTAL,0,0,0,0,1912,0,0,0,0,0,0,0,0,0
PO,0,0,0,0,0,0,0,0,33,0,0,0,0,0
CARO,0,0,0,0,0,0,0,0,21,0,0,0,0,0
DDANAT,0,0,0,0,0,0,0,0,3,0,0,0,0,0

Unique nodes across databases:

category,biolink:AnatomicalEntity,biolink:BiologicalProcess,biolink:Cell,biolink:CellularComponent,biolink:ChemicalSubstance,biolink:Disease,biolink:Gene,biolink:MacromolecularComplexMixin,biolink:MolecularActivity,biolink:NamedThing,biolink:OntologyClass,biolink:OrganismTaxon,biolink:PhenotypicFeature,biolink:Protein,biolink:RNAProduct,biolink:SequenceFeature
DB,,,,,,,,,,,,,,,,
Bgee,0,0,0,0,0,0,37322,0,0,0,0,0,0,0,0,0
CL,0,0,1678,0,157,0,0,0,0,41,148,21,0,328,0,0
DIANA-TarBase,0,0,0,0,0,0,18,0,0,0,0,0,0,0,468,0
Disgenet,0,0,0,0,0,0,2226,0,0,0,0,0,0,0,0,0
ENSEMBL,0,0,0,0,0,0,23675,0,0,0,0,0,0,86108,0,0
GO,0,30723,0,4519,0,0,0,0,12614,0,3756,0,0,0,0,0
GOA,0,0,0,0,0,0,0,1904,0,0,0,0,0,844,22776,0
HP,0,0,0,0,0,0,0,0,0,0,32,0,19162,0,0,0
MONDO,5348,0,1196,0,1214,28746,0,0,0,0,6636,1832,0,0,0,85
NPInter,0,0,0,0,0,0,0,0,0,0,0,0,0,26,21984,0
RNACentral,0,0,0,0,0,0,2887,0,0,0,0,0,0,0,60240,0
STRING,0,0,0,0,0,0,0,0,0,0,0,0,0,32,0,0
Uberon,10389,0,50,0,0,0,0,0,0,0,173,0,0,0,0,0

## Analyse edges predicates

In [3]:
print("Edges by predicate across databases:")
display(results["predicates"])

Edges by predicate across databases:

,GO,HP,MONDO,ENSEMBL,GOA,HPOA,Disgenet,Uberon,CL,Bgee,RNACentral,DIANA-TarBase,NPInter,STRING
biolink:subclass_of,66172,23137,71083,0,0,0,0,20799,25898,0,0,0,0,0
biolink:related_to,17595,0,27364,0,0,0,0,16662,19533,0,0,0,0,0
rdfs:subPropertyOf,3,0,237,0,0,0,0,98,295,0,0,0,0,0
owl:inverseOf,1,0,52,0,0,0,0,18,49,0,0,0,0,0
biolink:type,0,0,17,0,0,0,0,0,0,0,0,0,0,0
biolink:has_gene_product,0,0,0,93797,0,0,0,0,0,0,62925,0,0,0
biolink:actively_involved_in,0,0,0,0,193113,0,0,0,0,0,0,0,0,0
biolink:enables,0,0,0,0,127947,0,0,0,0,0,0,0,0,0
biolink:located_in,0,0,0,0,116221,0,0,0,0,0,0,0,0,0
biolink:part_of,0,0,0,0,24841,0,0,0,0,0,0,0,0,0
biolink:active_in,0,0,0,0,19171,0,0,0,0,0,0,0,0,0
biolink:acts_upstream_of_or_within,0,0,0,0,2300,0,0,0,0,0,0,0,0,0
biolink:contributes_to,0,0,0,0,930,0,0,0,0,0,0,0,0,0
biolink:colocalizes_with,0,0,0,0,897,0,0,0,0,0,0,0,0,0
biolink:acts_upstream_of,0,0,0,0,892,0,0,0,0,0,0,0,0,0
biolink:acts_upstream_of_positive_effect,0,0,0,0,96,0,0,0,0,0,0,0,0,0
biolink:acts_upstream_of_or_within_positive_effect,0,0,0,0,37,0,0,0,0,0,0,0,0,0
biolink:acts_upstream_of_negative_effect,0,0,0,0,30,0,0,0,0,0,0,0,0,0
biolink:acts_upstream_of_or_within_negative_effect,0,0,0,0,11,0,0,0,0,0,0,0,0,0
biolink:associated_with,0,0,0,0,0,0,867116,0,0,0,0,0,0,0
biolink:expressed_in,0,0,0,0,0,0,0,0,0,6851091,0,0,0,0
biolink:interacts_with,0,0,0,0,0,0,0,0,0,0,0,1256214,371519,10610496

## Pivot table for Sankey graph

In [4]:
print("Subject-Object prefix cross-tabulation for Sankey graph:")
display(results["sankey_pivot"])

Subject-Object prefix cross-tabulation for Sankey graph:

obj_prefix,BFO,BSPO,CARO,CHEBI,CHR,CL,DDANAT,ENSEMBL,ENVO,FOODON,...,OBO,OGMS,PATO,PO,RNACENTRAL,RO,SO,UBERON,UNIPROTKB,http
sub_prefix,,,,,,,,,,,,,,,,,,,,,
BFO,39,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,10,0,0,0,0
BSPO,13,14,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,0,0,0,0
CARO,4,0,27,0,0,0,0,0,0,0,...,0,0,6,0,0,0,0,0,0,0
CHEBI,18,0,0,4066,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CHR,0,0,0,0,285,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CL,115,0,213,0,0,6575,0,0,0,0,...,0,0,141,0,0,0,0,1887,1171,0
COMPLEXPORTAL,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSEMBL,0,0,0,0,0,17226,0,0,0,0,...,0,0,0,0,62925,0,0,482774,93797,0
ENVO,18,0,0,32,0,0,0,0,744,0,...,0,0,97,0,0,3,0,10,0,0
FOODON,4,0,0,1,0,0,0,0,0,244,...,0,0,6,0,0,1,0,6,0,0
GO,8,0,2,648,0,845,3,0,0,0,...,0,1,2,59,0,0,0,961,26,0
HP,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
IAO,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MF,4,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
MFOMD,0,0,0,0,0,0,0,0,0,0,...,0,3,0,0,0,0,0,0,0,0
MONDO,3,0,0,48,269,117,0,0,15,0,...,47,0,83,0,0,2,34,1016,0,4488
NBO,0,0,0,2,0,0,0,0,0,0,...,0,0,2,0,0,0,0,2,0,0
NCBITaxon,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NCIT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
OBO,6,10,0,310,0,0,0,0,55,0,...,884,0,8,0,0,30,0,0,0,0
OGMS,4,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
PATO,2,0,0,0,0,0,0,0,0,0,...,0,0,736,0,0,0,0,0,0,0
RNACENTRAL,0,0,0,0,0,0,0,502784,0,0,...,0,0,0,0,439,0,0,0,368378,0
RO,55,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,608,0,0,0,0
SO,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,104,0,0,0
UBERON,24,0,496,38,0,920,0,0,4,0,...,0,0,113,0,0,224,0,66485,6,0
UNIPROTKB,0,0,0,134,0,0,0,0,0,0,...,0,0,0,0,0,0,36,0,500510,0
http,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,3967,0,0,0